# Generated by Django 6.0.3 on 2026-05-16 05:03

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(default=123, max_length=255, verbose_name='cv_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='tax_code',
            field=models.CharField(default='0123456789', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('REVIEWING', 'Chờ xét duyệt'), ('INTERVIEW', 'Hẹn phỏng vấn'), ('ACCEPTED', 'Trúng tuyển'), ('REJECTED', 'Trượt'), ('WITHDRAWN', 'Ứng viên rút đơn'), ('CANCELLED', 'Đã hủy')], default='REVIEWING', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(limit_choices_to={'role': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='following_companies', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='jobs.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ gửi'), ('SENT', 'Đã gửi'), ('FAILED', 'Lỗi')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.companyfollow')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='companyfollow',
            index=models.Index(fields=['employer'], name='jobs_compan_employe_66ec31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfollow',
            unique_together={('candidate', 'employer')},
        ),
        migrations.AlterUniqueTogether(
            name='jobnotification',
            unique_together={('follow', 'job')},
        ),
    ]
