# Generated by Django 6.0.3 on 2026-05-17 04:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_is_premium_application_cv_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo_company',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
