# Generated by Django 6.0.3 on 2026-05-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_is_premium_application_cv_file_and_more'),
        ('jobs', '0002_rename_benefic_job_benefits_and_more'),
    ]

    operations = [
    ]
