# Generated by Django 6.0.3 on 2026-05-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_created_at_application_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfollow',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
