# Generated by Django 6.0.3 on 2026-05-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_application_unique_together_and_more"),
        ("jobs", "0006_workplaceimage"),
    ]

    operations = []
