# Generated by Django 6.0.3 on 2026-05-20 05:42

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_merge_20260520_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo_company',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.industry'),
        ),
    ]
