# Generated by Django 6.0.3 on 2026-05-22 11:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_employer_logo_company_alter_job_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
