# Generated by Django 6.0.3 on 2026-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_application_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='max_applicants',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
