# Generated by Django 6.0.3 on 2026-05-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_application_max_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='max_applicants',
        ),
        migrations.AddField(
            model_name='job',
            name='max_applicants',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
