# Generated by Django 6.0.3 on 2026-05-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_application_max_applicants_job_max_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_applicants',
            field=models.IntegerField(default=10),
        ),
    ]
