# Generated by Django 6.0.3 on 2026-05-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_max_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('OPENING', 'Đã duyệt'), ('CLOSED', 'Hết hạn')], default='OPENING', max_length=20),
        ),
    ]
