# Generated by Django 6.0.3 on 2026-05-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPENING', 'Đã duyệt'), ('CLOSED', 'Hết hạn')], default='OPENING', max_length=20),
        ),
    ]
