# Generated by Django 6.0.3 on 2026-05-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_cityzenid_alter_user_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Người dùng'), ('EMPLOYER', 'Nhà tuyển dụng')], default='USER', max_length=20),
        ),
    ]
